// Mock Notifications Data
export const notifications = [
  {
    id: 1,
    userId: 1,
    userRole: 'customer',
    type: 'booking-confirmed',
    title: 'Đặt lịch thành công',
    titleEn: 'Booking Confirmed',
    message: 'Lịch bảo dưỡng của bạn đã được xác nhận cho ngày 05/12/2024 lúc 09:00',
    messageEn: 'Your maintenance appointment has been confirmed for 05/12/2024 at 09:00',
    relatedId: 6,
    relatedType: 'order',
    icon: 'FiCheckCircle',
    iconColor: '#10B981',
    isRead: false,
    createdAt: '2024-12-01T08:45:00Z',
    link: '/customer/booking'
  },
  {
    id: 2,
    userId: 1,
    userRole: 'customer',
    type: 'service-reminder',
    title: 'Nhắc lịch bảo dưỡng',
    titleEn: 'Service Reminder',
    message: 'Xe VinFast VF e34 của bạn sắp đến hạn bảo dưỡng định kỳ vào 15/02/2025',
    messageEn: 'Your VinFast VF e34 is due for periodic maintenance on 15/02/2025',
    relatedId: 1,
    relatedType: 'vehicle',
    icon: 'FiCalendar',
    iconColor: '#F59E0B',
    isRead: false,
    createdAt: '2024-12-04T09:00:00Z',
    link: '/customer/booking'
  },
  {
    id: 3,
    userId: 1,
    userRole: 'customer',
    type: 'promotion',
    title: 'Ưu đãi đặc biệt',
    titleEn: 'Special Offer',
    message: 'Giảm 20% cho dịch vụ kiểm tra pin - Áp dụng đến 31/12/2024',
    messageEn: '20% off Battery Check Service - Valid until 31/12/2024',
    relatedId: null,
    relatedType: 'promotion',
    icon: 'FiGift',
    iconColor: '#EC4899',
    isRead: true,
    createdAt: '2024-11-30T10:00:00Z',
    link: '/customer/booking'
  },
  {
    id: 4,
    userId: 1,
    userRole: 'customer',
    type: 'invoice-ready',
    title: 'Hóa đơn đã sẵn sàng',
    titleEn: 'Invoice Ready',
    message: 'Hóa đơn INV-2024-001 cho dịch vụ bảo dưỡng ngày 20/11 đã sẵn sàng',
    messageEn: 'Invoice INV-2024-001 for maintenance service on 20/11 is ready',
    relatedId: 1,
    relatedType: 'invoice',
    icon: 'FiFileText',
    iconColor: '#3B82F6',
    isRead: true,
    createdAt: '2024-11-20T11:35:00Z',
    link: '/customer/invoices'
  },
  {
    id: 5,
    userId: 2,
    userRole: 'customer',
    type: 'service-completed',
    title: 'Dịch vụ hoàn thành',
    titleEn: 'Service Completed',
    message: 'Bảo dưỡng định kỳ nâng cao cho xe VinFast VF 8 đã hoàn thành',
    messageEn: 'Advanced periodic maintenance for VinFast VF 8 has been completed',
    relatedId: 2,
    relatedType: 'order',
    icon: 'FiCheckCircle',
    iconColor: '#10B981',
    isRead: false,
    createdAt: '2024-11-15T17:05:00Z',
    link: '/customer/history'
  },
  {
    id: 6,
    userId: 2,
    userRole: 'customer',
    type: 'rating-request',
    title: 'Đánh giá dịch vụ',
    titleEn: 'Rate Service',
    message: 'Hãy đánh giá dịch vụ bảo dưỡng ngày 15/11 để giúp chúng tôi cải thiện',
    messageEn: 'Please rate the maintenance service on 15/11 to help us improve',
    relatedId: 2,
    relatedType: 'order',
    icon: 'FiStar',
    iconColor: '#F59E0B',
    isRead: false,
    createdAt: '2024-11-16T08:00:00Z',
    link: '/customer/ratings'
  },
  {
    id: 7,
    userId: 3,
    userRole: 'customer',
    type: 'payment-received',
    title: 'Đã nhận thanh toán',
    titleEn: 'Payment Received',
    message: 'Chúng tôi đã nhận thanh toán 3.000.000đ cho hóa đơn INV-2024-003',
    messageEn: 'We have received payment of 3,000,000đ for invoice INV-2024-003',
    relatedId: 3,
    relatedType: 'invoice',
    icon: 'FiDollarSign',
    iconColor: '#10B981',
    isRead: true,
    createdAt: '2024-11-28T09:35:00Z',
    link: '/customer/invoices'
  },
  {
    id: 8,
    userId: 3,
    userRole: 'customer',
    type: 'booking-confirmed',
    title: 'Đặt lịch thành công',
    titleEn: 'Booking Confirmed',
    message: 'Lịch kiểm tra pin của bạn đã được xác nhận cho ngày 06/12/2024 lúc 08:00',
    messageEn: 'Your battery check appointment has been confirmed for 06/12/2024 at 08:00',
    relatedId: 13,
    relatedType: 'order',
    icon: 'FiCheckCircle',
    iconColor: '#10B981',
    isRead: false,
    createdAt: '2024-12-04T17:10:00Z',
    link: '/customer/booking'
  },
  {
    id: 9,
    userId: 4,
    userRole: 'customer',
    type: 'service-reminder',
    title: 'Nhắc lịch bảo dưỡng',
    titleEn: 'Service Reminder',
    message: 'Xe Hyundai Kona Electric của bạn sắp đến 10.000km',
    messageEn: 'Your Hyundai Kona Electric is approaching 10,000km',
    relatedId: 4,
    relatedType: 'vehicle',
    icon: 'FiCalendar',
    iconColor: '#F59E0B',
    isRead: true,
    createdAt: '2024-11-20T09:00:00Z',
    link: '/customer/booking'
  },
  {
    id: 10,
    userId: 5,
    userRole: 'customer',
    type: 'loyalty-points',
    title: 'Tích điểm thưởng',
    titleEn: 'Loyalty Points Earned',
    message: 'Bạn đã nhận 150 điểm từ dịch vụ bảo dưỡng ngày 25/11',
    messageEn: 'You have earned 150 points from maintenance service on 25/11',
    relatedId: 5,
    relatedType: 'order',
    icon: 'FiAward',
    iconColor: '#8B5CF6',
    isRead: false,
    createdAt: '2024-11-25T15:35:00Z',
    link: '/customer/profile'
  },
  {
    id: 11,
    userId: 6,
    userRole: 'customer',
    type: 'booking-confirmed',
    title: 'Đặt lịch thành công',
    titleEn: 'Booking Confirmed',
    message: 'Lịch bảo dưỡng của bạn đã được xác nhận cho ngày 10/12/2024 lúc 14:00',
    messageEn: 'Your maintenance appointment has been confirmed for 10/12/2024 at 14:00',
    relatedId: 7,
    relatedType: 'order',
    icon: 'FiCheckCircle',
    iconColor: '#10B981',
    isRead: true,
    createdAt: '2024-12-03T10:20:00Z',
    link: '/customer/booking'
  },
  {
    id: 12,
    userId: 7,
    userRole: 'customer',
    type: 'booking-confirmed',
    title: 'Đặt lịch thành công',
    titleEn: 'Booking Confirmed',
    message: 'Lịch thay lốp của bạn đã được xác nhận cho ngày 08/12/2024 lúc 10:00',
    messageEn: 'Your tire replacement appointment has been confirmed for 08/12/2024 at 10:00',
    relatedId: 8,
    relatedType: 'order',
    icon: 'FiCheckCircle',
    iconColor: '#10B981',
    isRead: false,
    createdAt: '2024-12-02T15:00:00Z',
    link: '/customer/booking'
  },
  {
    id: 13,
    userId: 8,
    userRole: 'customer',
    type: 'service-in-progress',
    title: 'Đang thực hiện dịch vụ',
    titleEn: 'Service In Progress',
    message: 'Dịch vụ rửa xe của bạn đang được thực hiện (45% hoàn thành)',
    messageEn: 'Your car wash service is in progress (45% completed)',
    relatedId: 9,
    relatedType: 'order',
    icon: 'FiLoader',
    iconColor: '#3B82F6',
    isRead: false,
    createdAt: '2024-12-05T11:30:00Z',
    link: '/customer/history'
  },
  {
    id: 14,
    userId: 9,
    userRole: 'customer',
    type: 'booking-confirmed',
    title: 'Đặt lịch thành công',
    titleEn: 'Booking Confirmed',
    message: 'Lịch bảo dưỡng nâng cao đã được xác nhận cho ngày 12/12/2024 lúc 08:00',
    messageEn: 'Your advanced maintenance appointment has been confirmed for 12/12/2024 at 08:00',
    relatedId: 10,
    relatedType: 'order',
    icon: 'FiCheckCircle',
    iconColor: '#10B981',
    isRead: true,
    createdAt: '2024-12-03T16:35:00Z',
    link: '/customer/booking'
  },
  {
    id: 15,
    userId: 10,
    userRole: 'customer',
    type: 'booking-confirmed',
    title: 'Đặt lịch thành công',
    titleEn: 'Booking Confirmed',
    message: 'Lịch bảo dưỡng và vá lốp đã được xác nhận cho ngày 15/12/2024 lúc 09:30',
    messageEn: 'Your maintenance and tire repair appointment has been confirmed for 15/12/2024 at 09:30',
    relatedId: 12,
    relatedType: 'order',
    icon: 'FiCheckCircle',
    iconColor: '#10B981',
    isRead: false,
    createdAt: '2024-12-04T11:15:00Z',
    link: '/customer/booking'
  },
  // Technician notifications
  {
    id: 16,
    userId: 1,
    userRole: 'technician',
    type: 'job-assigned',
    title: 'Công việc mới',
    titleEn: 'New Job Assigned',
    message: 'Bạn được giao kiểm tra pin cho xe Tesla Model 3 - ORD-2024-013',
    messageEn: 'You have been assigned battery check for Tesla Model 3 - ORD-2024-013',
    relatedId: 13,
    relatedType: 'order',
    icon: 'FiTool',
    iconColor: '#3B82F6',
    isRead: false,
    createdAt: '2024-12-04T17:05:00Z',
    link: '/technician/jobs'
  },
  {
    id: 17,
    userId: 2,
    userRole: 'technician',
    type: 'job-assigned',
    title: 'Công việc mới',
    titleEn: 'New Job Assigned',
    message: 'Bạn được giao cập nhật phần mềm cho xe VinFast VF e34 - ORD-2024-006',
    messageEn: 'You have been assigned software update for VinFast VF e34 - ORD-2024-006',
    relatedId: 6,
    relatedType: 'order',
    icon: 'FiTool',
    iconColor: '#3B82F6',
    isRead: false,
    createdAt: '2024-12-01T08:40:00Z',
    link: '/technician/jobs'
  },
  {
    id: 18,
    userId: 7,
    userRole: 'advisor',
    type: 'customer-inquiry',
    title: 'Yêu cầu tư vấn mới',
    titleEn: 'New Customer Inquiry',
    message: 'Khách hàng Nguyễn Văn An cần tư vấn về dịch vụ bảo dưỡng pin',
    messageEn: 'Customer Nguyen Van An needs consultation about battery maintenance',
    relatedId: 1,
    relatedType: 'customer',
    icon: 'FiMessageCircle',
    iconColor: '#10B981',
    isRead: false,
    createdAt: '2024-12-05T10:30:00Z',
    link: '/advisor/customers'
  }
];

// Notification types
export const notificationTypes = [
  { id: 'booking-confirmed', name: 'Xác nhận đặt lịch', nameEn: 'Booking Confirmed', icon: 'FiCheckCircle' },
  { id: 'service-reminder', name: 'Nhắc lịch', nameEn: 'Service Reminder', icon: 'FiCalendar' },
  { id: 'service-completed', name: 'Hoàn thành dịch vụ', nameEn: 'Service Completed', icon: 'FiCheckCircle' },
  { id: 'service-in-progress', name: 'Đang thực hiện', nameEn: 'Service In Progress', icon: 'FiLoader' },
  { id: 'payment-received', name: 'Nhận thanh toán', nameEn: 'Payment Received', icon: 'FiDollarSign' },
  { id: 'invoice-ready', name: 'Hóa đơn sẵn sàng', nameEn: 'Invoice Ready', icon: 'FiFileText' },
  { id: 'rating-request', name: 'Yêu cầu đánh giá', nameEn: 'Rating Request', icon: 'FiStar' },
  { id: 'promotion', name: 'Khuyến mãi', nameEn: 'Promotion', icon: 'FiGift' },
  { id: 'loyalty-points', name: 'Điểm thưởng', nameEn: 'Loyalty Points', icon: 'FiAward' },
  { id: 'job-assigned', name: 'Giao việc', nameEn: 'Job Assigned', icon: 'FiTool' },
  { id: 'customer-inquiry', name: 'Yêu cầu tư vấn', nameEn: 'Customer Inquiry', icon: 'FiMessageCircle' }
];

export default notifications;
