// Mock Parts Data
export const parts = [
  {
    id: 1,
    name: 'Má phanh trước',
    nameEn: 'Front Brake Pads',
    partNumber: 'BP-F-001',
    category: 'brake',
    brand: 'Bosch',
    description: 'Má phanh ceramic cao cấp cho xe điện',
    descriptionEn: 'Premium ceramic brake pads for electric vehicles',
    price: 1200000,
    stockQuantity: 45,
    minStockLevel: 10,
    unit: 'bộ',
    unitEn: 'set',
    supplier: 'Bosch Vietnam',
    warrantyMonths: 12,
    status: 'in-stock'
  },
  {
    id: 2,
    name: 'Má phanh sau',
    nameEn: 'Rear Brake Pads',
    partNumber: 'BP-R-001',
    category: 'brake',
    brand: 'Bosch',
    description: 'Má phanh ceramic cho phanh sau',
    descriptionEn: 'Ceramic brake pads for rear brakes',
    price: 1000000,
    stockQuantity: 38,
    minStockLevel: 10,
    unit: 'bộ',
    unitEn: 'set',
    supplier: 'Bosch Vietnam',
    warrantyMonths: 12,
    status: 'in-stock'
  },
  {
    id: 3,
    name: 'Lốp xe Michelin 235/55R19',
    nameEn: 'Michelin Tire 235/55R19',
    partNumber: 'TIRE-M-235',
    category: 'tire',
    brand: 'Michelin',
    description: 'Lốp xe tiết kiệm năng lượng cho xe điện',
    descriptionEn: 'Energy-efficient tire for electric vehicles',
    price: 4500000,
    stockQuantity: 24,
    minStockLevel: 8,
    unit: 'cái',
    unitEn: 'piece',
    supplier: 'Michelin Vietnam',
    warrantyMonths: 24,
    status: 'in-stock'
  },
  {
    id: 4,
    name: 'Lốp xe Bridgestone 225/50R18',
    nameEn: 'Bridgestone Tire 225/50R18',
    partNumber: 'TIRE-B-225',
    category: 'tire',
    brand: 'Bridgestone',
    description: 'Lốp xe êm ái, bền bỉ',
    descriptionEn: 'Comfortable and durable tire',
    price: 3800000,
    stockQuantity: 32,
    minStockLevel: 8,
    unit: 'cái',
    unitEn: 'piece',
    supplier: 'Bridgestone Vietnam',
    warrantyMonths: 24,
    status: 'in-stock'
  },
  {
    id: 5,
    name: 'Lọc gió cabin HEPA',
    nameEn: 'HEPA Cabin Air Filter',
    partNumber: 'FILTER-HEPA-001',
    category: 'filter',
    brand: 'Mann Filter',
    description: 'Lọc bụi mịn PM2.5, kháng khuẩn',
    descriptionEn: 'PM2.5 fine dust filter, antibacterial',
    price: 450000,
    stockQuantity: 68,
    minStockLevel: 15,
    unit: 'cái',
    unitEn: 'piece',
    supplier: 'Mann+Hummel Vietnam',
    warrantyMonths: 6,
    status: 'in-stock'
  },
  {
    id: 6,
    name: 'Nước làm mát EV chuyên dụng',
    nameEn: 'EV Coolant Fluid',
    partNumber: 'COOL-EV-5L',
    category: 'fluid',
    brand: 'Castrol',
    description: 'Nước làm mát cho hệ thống pin và động cơ điện',
    descriptionEn: 'Coolant for battery and electric motor systems',
    price: 800000,
    stockQuantity: 52,
    minStockLevel: 12,
    unit: 'chai 5L',
    unitEn: '5L bottle',
    supplier: 'Castrol Vietnam',
    warrantyMonths: 0,
    status: 'in-stock'
  },
  {
    id: 7,
    name: 'Cầu chì cao áp 400V',
    nameEn: 'High Voltage Fuse 400V',
    partNumber: 'FUSE-HV-400',
    category: 'electrical',
    brand: 'Littelfuse',
    description: 'Cầu chì bảo vệ hệ thống điện cao áp',
    descriptionEn: 'High voltage electrical system protection fuse',
    price: 350000,
    stockQuantity: 85,
    minStockLevel: 20,
    unit: 'cái',
    unitEn: 'piece',
    supplier: 'Littelfuse Asia',
    warrantyMonths: 12,
    status: 'in-stock'
  },
  {
    id: 8,
    name: 'Gạt mưa trước (cặp)',
    nameEn: 'Front Wiper Blades (Pair)',
    partNumber: 'WIPER-F-SET',
    category: 'accessory',
    brand: 'Bosch',
    description: 'Gạt mưa siêu sạch, không kêu',
    descriptionEn: 'Ultra-clean, silent wiper blades',
    price: 550000,
    stockQuantity: 42,
    minStockLevel: 10,
    unit: 'cặp',
    unitEn: 'pair',
    supplier: 'Bosch Vietnam',
    warrantyMonths: 12,
    status: 'in-stock'
  },
  {
    id: 9,
    name: 'Bóng đèn LED H7',
    nameEn: 'LED Headlight Bulb H7',
    partNumber: 'LED-H7-001',
    category: 'lighting',
    brand: 'Philips',
    description: 'Bóng đèn LED siêu sáng, tiết kiệm điện',
    descriptionEn: 'Ultra-bright LED bulb, energy-efficient',
    price: 650000,
    stockQuantity: 28,
    minStockLevel: 8,
    unit: 'cái',
    unitEn: 'piece',
    supplier: 'Philips Vietnam',
    warrantyMonths: 24,
    status: 'in-stock'
  },
  {
    id: 10,
    name: 'Giảm xóc trước',
    nameEn: 'Front Shock Absorber',
    partNumber: 'SHOCK-F-001',
    category: 'suspension',
    brand: 'KYB',
    description: 'Giảm xóc gas cao cấp',
    descriptionEn: 'Premium gas shock absorber',
    price: 2800000,
    stockQuantity: 16,
    minStockLevel: 4,
    unit: 'cái',
    unitEn: 'piece',
    supplier: 'KYB Asia',
    warrantyMonths: 24,
    status: 'in-stock'
  },
  {
    id: 11,
    name: 'Giảm xóc sau',
    nameEn: 'Rear Shock Absorber',
    partNumber: 'SHOCK-R-001',
    category: 'suspension',
    brand: 'KYB',
    description: 'Giảm xóc gas cho trục sau',
    descriptionEn: 'Gas shock absorber for rear axle',
    price: 2500000,
    stockQuantity: 18,
    minStockLevel: 4,
    unit: 'cái',
    unitEn: 'piece',
    supplier: 'KYB Asia',
    warrantyMonths: 24,
    status: 'in-stock'
  },
  {
    id: 12,
    name: 'Dung dịch rửa kính',
    nameEn: 'Windshield Washer Fluid',
    partNumber: 'WASHER-2L',
    category: 'fluid',
    brand: 'Rain-X',
    description: 'Nước rửa kính chống bám nước',
    descriptionEn: 'Water-repellent windshield washer',
    price: 120000,
    stockQuantity: 95,
    minStockLevel: 20,
    unit: 'chai 2L',
    unitEn: '2L bottle',
    supplier: 'ITW Vietnam',
    warrantyMonths: 0,
    status: 'in-stock'
  },
  {
    id: 13,
    name: 'Đĩa phanh trước',
    nameEn: 'Front Brake Rotor',
    partNumber: 'ROTOR-F-001',
    category: 'brake',
    brand: 'Brembo',
    description: 'Đĩa phanh thông gió cao cấp',
    descriptionEn: 'Premium ventilated brake rotor',
    price: 3200000,
    stockQuantity: 12,
    minStockLevel: 4,
    unit: 'cái',
    unitEn: 'piece',
    supplier: 'Brembo Asia',
    warrantyMonths: 24,
    status: 'in-stock'
  },
  {
    id: 14,
    name: 'Đĩa phanh sau',
    nameEn: 'Rear Brake Rotor',
    partNumber: 'ROTOR-R-001',
    category: 'brake',
    brand: 'Brembo',
    description: 'Đĩa phanh đặc cho trục sau',
    descriptionEn: 'Solid brake rotor for rear axle',
    price: 2800000,
    stockQuantity: 14,
    minStockLevel: 4,
    unit: 'cái',
    unitEn: 'piece',
    supplier: 'Brembo Asia',
    warrantyMonths: 24,
    status: 'in-stock'
  },
  {
    id: 15,
    name: 'Cáp sạc Type 2 (5m)',
    nameEn: 'Type 2 Charging Cable (5m)',
    partNumber: 'CABLE-T2-5M',
    category: 'charging',
    brand: 'Phoenix Contact',
    description: 'Cáp sạc AC 32A chuyên dụng',
    descriptionEn: 'Professional AC charging cable 32A',
    price: 4500000,
    stockQuantity: 8,
    minStockLevel: 3,
    unit: 'cái',
    unitEn: 'piece',
    supplier: 'Phoenix Contact Asia',
    warrantyMonths: 36,
    status: 'in-stock'
  },
  {
    id: 16,
    name: 'Bộ cảm biến áp suất lốp TPMS',
    nameEn: 'TPMS Tire Pressure Sensor Set',
    partNumber: 'TPMS-SET-4',
    category: 'electrical',
    brand: 'Schrader',
    description: 'Bộ 4 cảm biến áp suất lốp',
    descriptionEn: 'Set of 4 tire pressure sensors',
    price: 3500000,
    stockQuantity: 6,
    minStockLevel: 2,
    unit: 'bộ',
    unitEn: 'set',
    supplier: 'Schrader Vietnam',
    warrantyMonths: 24,
    status: 'low-stock'
  },
  {
    id: 17,
    name: 'Thanh giằng cân bằng trước',
    nameEn: 'Front Stabilizer Bar',
    partNumber: 'STAB-F-001',
    category: 'suspension',
    brand: 'Moog',
    description: 'Thanh cân bằng chống lật',
    descriptionEn: 'Anti-roll stabilizer bar',
    price: 1800000,
    stockQuantity: 22,
    minStockLevel: 5,
    unit: 'cái',
    unitEn: 'piece',
    supplier: 'Moog Asia',
    warrantyMonths: 24,
    status: 'in-stock'
  },
  {
    id: 18,
    name: 'Pin 12V phụ trợ',
    nameEn: '12V Auxiliary Battery',
    partNumber: 'BATT-12V-AUX',
    category: 'battery',
    brand: 'Varta',
    description: 'Pin 12V cho hệ thống phụ trợ',
    descriptionEn: '12V battery for auxiliary systems',
    price: 2200000,
    stockQuantity: 15,
    minStockLevel: 4,
    unit: 'cái',
    unitEn: 'piece',
    supplier: 'Varta Vietnam',
    warrantyMonths: 24,
    status: 'in-stock'
  },
  {
    id: 19,
    name: 'Gối đỡ động cơ',
    nameEn: 'Motor Mount',
    partNumber: 'MOUNT-M-001',
    category: 'engine',
    brand: 'Hutchinson',
    description: 'Gối cao su chống rung động cơ điện',
    descriptionEn: 'Rubber anti-vibration motor mount',
    price: 1500000,
    stockQuantity: 10,
    minStockLevel: 3,
    unit: 'cái',
    unitEn: 'piece',
    supplier: 'Hutchinson Asia',
    warrantyMonths: 18,
    status: 'in-stock'
  },
  {
    id: 20,
    name: 'Bộ ốc vít bảo dưỡng',
    nameEn: 'Maintenance Bolt Set',
    partNumber: 'BOLT-MAIN-SET',
    category: 'accessory',
    brand: 'Generic',
    description: 'Bộ ốc vít thay thế cho bảo dưỡng định kỳ',
    descriptionEn: 'Replacement bolt set for periodic maintenance',
    price: 250000,
    stockQuantity: 120,
    minStockLevel: 30,
    unit: 'bộ',
    unitEn: 'set',
    supplier: 'Local Supplier',
    warrantyMonths: 6,
    status: 'in-stock'
  }
];

// Parts categories for filtering
export const partCategories = [
  { id: 'all', name: 'Tất cả phụ tùng', nameEn: 'All Parts' },
  { id: 'brake', name: 'Phanh', nameEn: 'Brake' },
  { id: 'tire', name: 'Lốp xe', nameEn: 'Tire' },
  { id: 'filter', name: 'Lọc gió', nameEn: 'Filter' },
  { id: 'fluid', name: 'Dung dịch', nameEn: 'Fluid' },
  { id: 'electrical', name: 'Điện', nameEn: 'Electrical' },
  { id: 'lighting', name: 'Đèn', nameEn: 'Lighting' },
  { id: 'suspension', name: 'Hệ thống treo', nameEn: 'Suspension' },
  { id: 'charging', name: 'Sạc', nameEn: 'Charging' },
  { id: 'battery', name: 'Pin', nameEn: 'Battery' },
  { id: 'engine', name: 'Động cơ', nameEn: 'Engine' },
  { id: 'accessory', name: 'Phụ kiện', nameEn: 'Accessory' }
];

export default parts;
