// Mock Reviews Data
export const reviews = [
  {
    id: 1,
    orderId: 1,
    customerId: 1,
    vehicleId: 1,
    technicianId: 1,
    serviceIds: [1, 3],
    rating: 5,
    title: 'Dịch vụ xuất sắc!',
    titleEn: 'Excellent service!',
    comment: 'Kỹ thuật viên Hùng rất chuyên nghiệp, kiểm tra pin kỹ lưỡng. Xe chạy êm hơn sau bảo dưỡng.',
    commentEn: 'Technician Hung is very professional, thorough battery check. Car runs smoother after maintenance.',
    serviceQuality: 5,
    staffAttitude: 5,
    cleanliness: 5,
    pricing: 5,
    timeliness: 5,
    wouldRecommend: true,
    photos: [],
    technicianResponse: 'Cảm ơn anh đã tin tưởng sử dụng dịch vụ. Rất vui khi được phục vụ!',
    technicianResponseEn: 'Thank you for trusting our service. It was a pleasure to serve you!',
    status: 'published',
    createdAt: '2024-11-21T09:30:00Z',
    respondedAt: '2024-11-21T14:00:00Z'
  },
  {
    id: 2,
    orderId: 2,
    customerId: 2,
    vehicleId: 2,
    technicianId: 2,
    serviceIds: [2, 7],
    rating: 5,
    title: 'Chuyên nghiệp',
    titleEn: 'Professional',
    comment: 'Cập nhật phần mềm nhanh chóng, giải thích rõ ràng các tính năng mới. Rất hài lòng!',
    commentEn: 'Quick software update, clear explanation of new features. Very satisfied!',
    serviceQuality: 5,
    staffAttitude: 5,
    cleanliness: 4,
    pricing: 5,
    timeliness: 5,
    wouldRecommend: true,
    photos: [],
    technicianResponse: 'Cảm ơn chị! Mọi thắc mắc về phần mềm vui lòng liên hệ em nhé.',
    technicianResponseEn: 'Thank you! Please contact me if you have any questions about the software.',
    status: 'published',
    createdAt: '2024-11-16T10:00:00Z',
    respondedAt: '2024-11-16T15:30:00Z'
  },
  {
    id: 3,
    orderId: 3,
    customerId: 3,
    vehicleId: 3,
    technicianId: 3,
    serviceIds: [6],
    rating: 4,
    title: 'Tốt nhưng hơi lâu',
    titleEn: 'Good but took a bit long',
    comment: 'Phanh giờ không còn kêu nữa, rất tốt. Tuy nhiên thời gian thực hiện lâu hơn dự kiến một chút.',
    commentEn: 'Brakes no longer squeak, very good. However, it took a bit longer than expected.',
    serviceQuality: 5,
    staffAttitude: 4,
    cleanliness: 4,
    pricing: 3,
    timeliness: 3,
    wouldRecommend: true,
    photos: [],
    technicianResponse: 'Xin lỗi anh vì thời gian chờ đợi. Do phải thay đĩa phanh nên mất thêm thời gian. Cảm ơn anh đã thông cảm!',
    technicianResponseEn: 'Sorry for the wait time. It took longer because we had to replace the brake rotor. Thank you for your understanding!',
    status: 'published',
    createdAt: '2024-11-29T11:00:00Z',
    respondedAt: '2024-11-29T16:20:00Z'
  },
  {
    id: 4,
    orderId: 4,
    customerId: 4,
    vehicleId: 4,
    technicianId: 4,
    serviceIds: [10],
    rating: 5,
    title: 'Điều hòa mát lạnh trở lại',
    titleEn: 'AC is cold again',
    comment: 'Điều hòa giờ mát lạnh như mới. Kỹ thuật viên Anh nhiệt tình, giá cả hợp lý.',
    commentEn: 'AC is now as cold as new. Technician Anh is enthusiastic, reasonable price.',
    serviceQuality: 5,
    staffAttitude: 5,
    cleanliness: 5,
    pricing: 5,
    timeliness: 5,
    wouldRecommend: true,
    photos: [],
    technicianResponse: 'Cảm ơn anh! Nhớ thay lọc gió cabin định kỳ 6 tháng/lần để giữ điều hòa luôn mát nhé.',
    technicianResponseEn: 'Thank you! Remember to replace the cabin air filter every 6 months to keep the AC cold.',
    status: 'published',
    createdAt: '2024-10-29T08:30:00Z',
    respondedAt: '2024-10-29T10:00:00Z'
  },
  {
    id: 5,
    orderId: 5,
    customerId: 5,
    vehicleId: 5,
    technicianId: 1,
    serviceIds: [1, 8, 9],
    rating: 5,
    title: 'Gói combo rất đáng giá',
    titleEn: 'Great value combo package',
    comment: 'Gói bảo dưỡng + vệ sinh rất đáng giá. Xe sạch sẽ, chạy êm. Kỹ thuật viên Hùng kinh nghiệm!',
    commentEn: 'Maintenance + cleaning combo is great value. Car is clean and runs smooth. Technician Hung is experienced!',
    serviceQuality: 5,
    staffAttitude: 5,
    cleanliness: 5,
    pricing: 5,
    timeliness: 5,
    wouldRecommend: true,
    photos: [],
    technicianResponse: 'Cảm ơn chị! Lần sau có thể đặt gói combo để được giảm giá thêm nhé.',
    technicianResponseEn: 'Thank you! Next time you can book the combo package for extra discount.',
    status: 'published',
    createdAt: '2024-11-26T08:00:00Z',
    respondedAt: '2024-11-26T11:30:00Z'
  },
  {
    id: 15,
    orderId: 15,
    customerId: 1,
    vehicleId: 1,
    technicianId: 2,
    serviceIds: [15],
    rating: 5,
    title: 'Nhanh gọn',
    titleEn: 'Quick and efficient',
    comment: 'Thay nước làm mát nhanh, sạch sẽ. Giá cả hợp lý.',
    commentEn: 'Quick coolant replacement, clean work. Reasonable price.',
    serviceQuality: 5,
    staffAttitude: 5,
    cleanliness: 5,
    pricing: 5,
    timeliness: 5,
    wouldRecommend: true,
    photos: [],
    technicianResponse: 'Cảm ơn anh! Nhớ kiểm tra mức nước làm mát định kỳ nhé.',
    technicianResponseEn: 'Thank you! Remember to check the coolant level periodically.',
    status: 'published',
    createdAt: '2024-09-11T09:00:00Z',
    respondedAt: '2024-09-11T14:20:00Z'
  },
  {
    id: 16,
    orderId: 16,
    customerId: 3,
    vehicleId: 3,
    technicianId: 1,
    serviceIds: [2, 7, 15],
    rating: 5,
    title: 'Bảo dưỡng lớn rất kỹ lưỡng',
    titleEn: 'Very thorough major maintenance',
    comment: 'Bảo dưỡng 15.000km rất kỹ càng. Kỹ thuật viên Hùng giải thích rõ từng hạng mục. Xe như mới!',
    commentEn: '15,000km maintenance very thorough. Technician Hung explained each item clearly. Car feels like new!',
    serviceQuality: 5,
    staffAttitude: 5,
    cleanliness: 5,
    pricing: 5,
    timeliness: 4,
    wouldRecommend: true,
    photos: [],
    technicianResponse: 'Cảm ơn anh! Pin và động cơ xe anh trong tình trạng rất tốt, yên tâm sử dụng nhé.',
    technicianResponseEn: 'Thank you! Your battery and motor are in very good condition, use with confidence.',
    status: 'published',
    createdAt: '2024-08-16T10:30:00Z',
    respondedAt: '2024-08-16T15:00:00Z'
  },
  {
    id: 17,
    orderId: 17,
    customerId: 5,
    vehicleId: 5,
    technicianId: 3,
    serviceIds: [11],
    rating: 5,
    title: 'Giảm xóc mới chạy êm hơn nhiều',
    titleEn: 'New shock absorbers much smoother',
    comment: 'Thay giảm xóc xong xe chạy êm ái hơn rất nhiều. Cô Hương tư vấn tận tình!',
    commentEn: 'After replacing shock absorbers, the car runs much smoother. Ms. Huong gave thoughtful advice!',
    serviceQuality: 5,
    staffAttitude: 5,
    cleanliness: 5,
    pricing: 5,
    timeliness: 4,
    wouldRecommend: true,
    photos: [],
    technicianResponse: 'Cảm ơn chị! Giảm xóc KYB chất lượng cao, chị yên tâm sử dụng nhé.',
    technicianResponseEn: 'Thank you! KYB shock absorbers are high quality, use with confidence.',
    status: 'published',
    createdAt: '2024-07-21T11:00:00Z',
    respondedAt: '2024-07-21T16:30:00Z'
  },
  {
    id: 18,
    orderId: 18,
    customerId: 9,
    vehicleId: 9,
    technicianId: 2,
    serviceIds: [1, 7],
    rating: 4,
    title: 'Bảo dưỡng tốt',
    titleEn: 'Good maintenance',
    comment: 'Bảo dưỡng định kỳ tốt, cập nhật phần mềm mượt mà. Chờ đợi hơi lâu một chút.',
    commentEn: 'Good periodic maintenance, smooth software update. Waiting time was a bit long.',
    serviceQuality: 5,
    staffAttitude: 4,
    cleanliness: 4,
    pricing: 4,
    timeliness: 3,
    wouldRecommend: true,
    photos: [],
    technicianResponse: 'Xin lỗi chị vì thời gian chờ. Hôm đó có nhiều khách hàng hơn dự kiến. Lần sau em sẽ cố gắng nhanh hơn!',
    technicianResponseEn: 'Sorry for the wait. We had more customers than expected that day. Will try to be faster next time!',
    status: 'published',
    createdAt: '2024-06-26T09:30:00Z',
    respondedAt: '2024-06-26T14:00:00Z'
  },
  {
    id: 19,
    orderId: 19,
    customerId: 7,
    vehicleId: 7,
    technicianId: 1,
    serviceIds: [3],
    rating: 5,
    title: 'Pin vẫn còn rất tốt',
    titleEn: 'Battery still in great condition',
    comment: 'Kiểm tra pin kỹ lưỡng, kỹ thuật viên cho xem kết quả chi tiết. Pin còn 96% capacity, rất yên tâm!',
    commentEn: 'Thorough battery check, technician showed detailed results. Battery at 96% capacity, very reassuring!',
    serviceQuality: 5,
    staffAttitude: 5,
    cleanliness: 5,
    pricing: 5,
    timeliness: 5,
    wouldRecommend: true,
    photos: [],
    technicianResponse: 'Cảm ơn chị! Pin Tesla chất lượng cao, cứ yên tâm sử dụng. Nhớ sạc đúng cách để bảo vệ pin nhé.',
    technicianResponseEn: 'Thank you! Tesla batteries are high quality, use with confidence. Remember to charge properly to protect the battery.',
    status: 'published',
    createdAt: '2024-05-11T10:00:00Z',
    respondedAt: '2024-05-11T15:20:00Z'
  },
  {
    id: 20,
    orderId: 20,
    customerId: 2,
    vehicleId: 2,
    technicianId: 4,
    serviceIds: [8, 9],
    rating: 5,
    title: 'Vệ sinh nội thất sạch như mới',
    titleEn: 'Interior cleaning like new',
    comment: 'Vệ sinh nội thất rất kỹ, ghế da sạch bóng. Rửa xe đánh bóng cũng rất đẹp. Hài lòng 100%!',
    commentEn: 'Very thorough interior cleaning, leather seats shiny clean. Car wash and polish also beautiful. 100% satisfied!',
    serviceQuality: 5,
    staffAttitude: 5,
    cleanliness: 5,
    pricing: 5,
    timeliness: 5,
    wouldRecommend: true,
    photos: [],
    technicianResponse: 'Cảm ơn chị! Chị nhớ bảo dưỡng da ghế định kỳ 3-6 tháng để giữ được độ bền nhé.',
    technicianResponseEn: 'Thank you! Remember to maintain the leather seats every 3-6 months to preserve durability.',
    status: 'published',
    createdAt: '2024-04-19T08:30:00Z',
    respondedAt: '2024-04-19T11:00:00Z'
  }
];

// Review statistics helper
export const getReviewStats = (reviews) => {
  const total = reviews.length;
  const averageRating = reviews.reduce((sum, r) => sum + r.rating, 0) / total;
  const ratingDistribution = {
    5: reviews.filter(r => r.rating === 5).length,
    4: reviews.filter(r => r.rating === 4).length,
    3: reviews.filter(r => r.rating === 3).length,
    2: reviews.filter(r => r.rating === 2).length,
    1: reviews.filter(r => r.rating === 1).length
  };
  const wouldRecommendCount = reviews.filter(r => r.wouldRecommend).length;
  const recommendationRate = (wouldRecommendCount / total) * 100;

  return {
    total,
    averageRating: Math.round(averageRating * 10) / 10,
    ratingDistribution,
    recommendationRate: Math.round(recommendationRate)
  };
};

// Review aspects for detailed ratings
export const reviewAspects = [
  { id: 'serviceQuality', name: 'Chất lượng dịch vụ', nameEn: 'Service Quality' },
  { id: 'staffAttitude', name: 'Thái độ nhân viên', nameEn: 'Staff Attitude' },
  { id: 'cleanliness', name: 'Vệ sinh', nameEn: 'Cleanliness' },
  { id: 'pricing', name: 'Giá cả', nameEn: 'Pricing' },
  { id: 'timeliness', name: 'Thời gian', nameEn: 'Timeliness' }
];

export default reviews;
